Ref-014, As MC admin, I can see which assigned members have attended their first MC meeting
kanzucode/angie-client pull request #50
Opened 2021-04-27 22:08 UTC by dhotim

**What does this PR do?**

- This PR adds a feature that allows MC admins to view first time guests. These are members who have attended an MC event for the first time.

**Description of tasks?**
- MC admins are now able to see new members who have attended an MC event.

**How to manually test this?**
- Under Reports, select a particular report to view then select members who have attended the MC. There should be a “First Time Guests” tab next to it to show members who have attended for the first time.

![image](https://user-images.githubusercontent.com/5897163/116318728-83f93a80-a7b5-11eb-9963-1780eea78e20.png)

![image](https://user-images.githubusercontent.com/5897163/116318807-9ffcdc00-a7b5-11eb-92d2-97b9cc90826a.png)

2021-04-30 10:05 UTC, ekastimo commented
Hi @dhotim , I was wondering whether we can avoid a new tab by just appending a guest tag, of the attendance list for people who are guests. Something like the image below
![image](https://user-images.githubusercontent.com/12415442/116680741-b45af780-a9b4-11eb-93fc-a271f15200e7.png)

2021-04-30 10:07 UTC, ekastimo requested changes
I left some comments and an image

2021-05-07 13:34 UTC, dhotim commented
I have made the changes requested.

![image](https://user-images.githubusercontent.com/5897163/117457367-70826800-af49-11eb-80d4-bd7324fe821e.png)

2021-05-17 07:16 UTC, ekastimo approved these changes

2021-05-17 07:17 UTC, merged